import type { TeamMember } from "../interfaces";

export const teamMembers: TeamMember[] = [
    { name: "Dr Rajesh Jalnekar", title: "Director, VIT College, Pune", image: "img/team/rajesh-jalnekar.jpg" },
    { name: "Dr Rajesh Tapadia", title: "MS, Owner of Ganga Nursing Hospital, Pune", image: "img/team/rajesh-tapadia.jpg" },
    { name: "Dr Makarand Upakare", title: "Dean, VIT College, Pune", image: "img/team/makarand-upakare.jpg" },
    { name: "Mr Jay Gehlot", title: "Principal Software Engineer, DELL", image: "img/team/jay-gehlot.jpg" },
    { name: "Mr Niranjan Pendakar", title: "Staff Engineer, I-nautix", image: "img/team/niranjan-pendakar.jpg" },
    { name: "Mr Nirendra Awasthi", title: "Sr Manager, Microsoft", image: "img/team/nirendra-awasthi.jpg" },
    { name: "Dr Himanshu Asnani", title: "Asst Prof, TIFR", image: "img/team/himanshu-asnani.jpg" },
    { name: "Dr Gajendranath Chowdhury", title: "Asst Prof, IIT-H", image: "img/team/gajendranath-chowdhury.jpg" },
    { name: "Dr Hari Krishnan", title: "Associate Dean & Professor, NITW", image: "img/team/hari-krishnan.jpg" },
    { name: "Dr Lalan Kumar", title: "Professor, Dept of Electrical & Electronics, IITD", image: "img/team/lalan-kumar.jpg" },
    { name: "Mr Vinay Jain", title: "MS, IISc Bangalore, TRDDC", image: "img/team/vinay-jain.jpg" },
    { name: "Mr Anand Yeolakar", title: "MSc, IITB, TRDDC", image: "img/team/anand-yeolakar.jpg" },
    { name: "Dr Mohan SC", title: "Asst Professor, BITS Hyderabad", image: "img/team/mohan-sc.jpg" },
    { name: "Dr Karthick Subramanium", title: "Dean, VIT College, Pune", image: "img/team/karthick-subramanium.jpg" },
    { name: "Mr Amber Sayal", title: "Head of Strategic Initiatives, TCS", image: "img/team/amber-sayal.jpg" },
    { name: "Mr Abhijit Kamble", title: "Sales Performance Management Consultant, OpenSymmetry", image: "img/team/abhijit-kamble.jpg" },
    { name: "Mr Gaurav Fushe", title: "Network Software Validation Engineer, Intel India Tech Ltd", image: "img/team/gaurav-fushe.jpg" },
    { name: "Mr Vivek Karkade", title: "Qualification Project Leader, Airbus India Pvt Ltd", image: "img/team/vivek-karkade.jpg" },
    { name: "Mr Prasad Patharkar", title: "Sr QA Automation Engineer, Xpanxion", image: "img/team/prasad-patharkar.jpg" },
    { name: "Mr Rahul Pitrubhakt", title: "Process Engineer, TCE", image: "img/team/rahul-pitrubhakt.jpg" },
    { name: "Mr Jitendra Savanur", title: "Technology Analyst, Goldman Sachs, New York", image: "img/team/jitendra-savanur.jpg" },
    { name: "Mr Anshu Raina", title: "Intel, Silicon Valley", image: "img/team/anshu-raina.jpg" },
    { name: "Mr Roshan Karande", title: "Associate Engineer, Mastercard", image: "img/team/roshan-karande.jpg" },
    { name: "Mr Prabhat Kumar", title: "Software Engineer III, Google", image: "img/team/prabhat-kumar.jpg" },
    { name: "Mr Priyesh Singh", title: "Software Engineer, Barclays", image: "img/team/priyesh-singh.jpg" },
    { name: "Mr Pushpakraj Sakhlikar", title: "Software Engineer, HPCL (IITGn)", image: "img/team/pushpakraj-sakhlikar.jpg" },
    { name: "Mr Amit Chauhan", title: "Sr Engineering Manager (R&D), DELL", image: "img/team/amit-chauhan.jpg" },
    { name: "Mr Anand Patil", title: "Chief Education Architect, KPIT", image: "img/team/anand-patil.jpg" },
    { name: "Mr Piyush Mittal", title: "Machine Learning Solution Architect, German Edge Cloud", image: "img/team/piyush-mittal.jpg" },
    { name: "Mr Akshay Mantriwar", title: "Full Stack Developer, Techprimelab Software Pvt Ltd", image: "img/team/akshay-mantriwar.jpg" },
    { name: "Mr Ashwin Wadte", title: "System Software Engineer, Nvidia", image: "img/team/ashwin-wadte.jpg" },
    { name: "Mr Digvijay Yadav", title: "MTech, IITB, Researcher, TRDDC", image: "img/team/digvijay-yadav.jpg" },
];
